### ISSUE TITLE
Label isn't rendered on selected options, nor is the "X" icon to delete an option

### ISSUE THREAD

**Issue by dwtompkins** [rmorse/wp-token-multiselect-control#1]
Hi,

I followed the Gutenberg rabbit hole to this repo, and it's a fantastic custom component.
I'm having an issue where selected options aren't showing their label or the "X" to remove the option:

![image](https://user-images.githubusercontent.com/71997022/118185863-08c99280-b40b-11eb-9278-8d6665ec38eb.png)
![image](https://user-images.githubusercontent.com/71997022/118185915-1717ae80-b40b-11eb-9284-66a2587b6282.png)

The little gray square is the only thing that's rendering. If I hover over the right half (which is difficult because it's so small) I'm still able to get the tooltip for removing that option. I can click it, and the option is removed.

I'm compiling without errors. Here's the block.js file of my code (started with `npx create-guten-block`):
https://gist.github.com/dwtompkins/8f4bd679debef3ea64e35e5b4604756b

**Comment by dwtompkins** [comment]
![image](https://user-images.githubusercontent.com/71997022/118188863-09642800-b40f-11eb-9572-0d99c84e31ca.png)
It looks like it's returning "null" instead of the label: post.title.rendered. And the "X" to remove an option is there, but it isn't styling properly

**Comment by dwtompkins** [comment]
Looks like I didn't read the Readme well enough. I was trying to attach an object as the value, but it looks like you've clearly outlined that it should take an array of strings, not objects. I think that's why my title wasn't showing up. It seems like it's also a feature (perhaps?) that the they get tucked-in and tiny when you click away. I think there might've been a change in the styling that made the "X" disappear.

**Comment by rmorse** [comment]
I love it when an issue closes itself ;)

**Comment by dwtompkins** [comment]
Haha
It did seem odd to me that it's grabbing the label from the value rather than from the label... I'd really like to be able to pass an object with post data. I think it might just have to be saved to meta or associated with the block in a different way. Or maybe it was taking it from the label, but it wouldn't resolve until I changed the value into a flat array.

You might still have an issue with the `size=24` attribute on that svg element. I had to add a `height=24` or `width=24` for it to display. Seems like size might've been deprecated or something. Just FYI, probably won't do a pull request for it. haha

**Comment by rmorse** [comment]
@dwtompkins - sounds like something is not quite right.

You should able to supply this:

```
[
	{
	    value: 'post',
	    label: 'Post',
	},
	{
	    value: 'page',
	    label: 'Page',
	},
	{
	    value: 'product',
	    label: 'Product',
	},
]
```

And it should search on the label + display the option by label, and match on the _value_ internally.

If you were using it to display a list of posts, you could pass post ID as `value`, and post title as the label.

As an example with an array of posts (as objects) you could do this:

```
const options = posts.map( ( post ) => {
    return { value: post.id, label: post.title };
}
```
Then your values would be an array something like this:
```[ 12, 94, 33 ]``` 
Which would correspond to the selected post IDs.

I'm using this at the moment in a few places and this is how it _should_ be behaving - let me know if that is not the case.

Also regarding the styling, I have an idea.

This component is heavily based on `FormTokenField` - https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/form-token-field 

In fact, there is no styling added all, and it just inherits the CSS from the Gutenberg component.  If it's not displaying correctly, maybe something is also affecting the styling of this component.

If you are loading this on a custom admin page, you would need to ensure you enqueue the `wp-components` css file (to load the default styles) - however, if you are adding this to a block, those styles should already be there.

- re-opening for now until we know more

**Comment by dwtompkins** [comment]
Hey thanks for providing some clarity for me. I now have an array (called _availablePosts_) that's working with the post title as the label and the post id as value:

```
function getOptions( type ) {
	const location = '/wp/v2/' + type; // WordPress API, uses json request with post type
	const availablePosts = []; // Empty array to hold available posts
	apiFetch( { path: location } ).then( ( posts ) => { // Query
		if ( posts ) { // If query retrieved posts
			posts.forEach( ( post ) => { // Loop through posts, retrieving post info
				availablePosts.push( {
					value: parseInt( post.id ),
					label: decodeEntities( post.title.rendered ),
				} );
			} );
		} else {
			availablePosts.push( {
				value: 0,
				label: 'Loading...',
			} );
		}
	} );

	return availablePosts;
}
```

I was hoping I could set `value` as an object, but that didn't seem to work. For example:


```
[{
	value: {
		id: parseInt( post.id ),
		author: post.author,
		etc: post.etc,
		...
	},
	label: decodeEntities( post.title.renderd )
},
{
	value: { ... },
	label: string
}]
```

The thought was that I could pull in more post data points for previewing the front-end block from within Gutenberg's editor. Seems like that might not be the best practice...

Anytime I tried setting `value` as an object (like in the example above), I'm having trouble getting it to report as a proper object on the front end. I messed around with some `JSON.stringify` stuff, but I keep getting a string: `"[object Object]"`.

Having `post.id` as the value of `value` works just fine, and that's where I landed after struggling to get an object into the value.

### Styling

I have `'wp-edit-blocks'` enqueued, and I've read that this should enqueue `'wp-components'` along with it. I tried adding `'wp-components'` (just in case); but that didn't seem to have any effect on the "X" situation... That was a clever thought though. Here's my scripts and styles:

```
function ireta_blocks_cgb_block_assets() { // phpcs:ignore
  // Register block styles for both frontend + backend.
  wp_register_style(
    'ireta_blocks-cgb-style-css', // Handle.
    plugins_url( 'dist/blocks.style.build.css', dirname( __FILE__ ) ), // Block style CSS.
    is_admin() ? array( 'wp-editor' ) : null, // Dependency to include the CSS after it.
    null // filemtime( plugin_dir_path( __DIR__ ) . 'dist/blocks.style.build.css' ) // Version: File modification time.
  );

  // Register block editor script for backend.
  wp_register_script(
    'ireta_blocks-cgb-block-js', // Handle.
    plugins_url( '/dist/blocks.build.js', dirname( __FILE__ ) ), // Block.build.js: We register the block here. Built with Webpack.
    array( 'wp-blocks', 'wp-i18n', 'wp-components', 'wp-element', 'wp-editor' ), // Dependencies, defined above.
    null, // filemtime( plugin_dir_path( __DIR__ ) . 'dist/blocks.build.js' ), // Version: filemtime — Gets file modification time.
    true // Enqueue the script in the footer.
  );

  // Register block editor styles for backend.
  wp_register_style(
    'ireta_blocks-cgb-block-editor-css', // Handle.
    plugins_url( 'dist/blocks.editor.build.css', dirname( __FILE__ ) ), // Block editor CSS.
    array( 'wp-edit-blocks' ), // Dependency to include the CSS after it.
    null // filemtime( plugin_dir_path( __DIR__ ) . 'dist/blocks.editor.build.css' ) // Version: File modification time.
  );

  // WP Localized globals. Use dynamic PHP stuff in JavaScript via `cgbGlobal` object.
  wp_localize_script(
    'ireta_blocks-cgb-block-js',
    'cgbGlobal', // Array containing dynamic data for a JS Global.
    [
      'pluginDirPath' => plugin_dir_path( __DIR__ ),
      'pluginDirUrl'  => plugin_dir_url( __DIR__ ),
      // Add more data here that you want to access from `cgbGlobal` object.
    ]
  );

  /**
   * Register Gutenberg block on server-side.
   *
   * Register the block on server-side to ensure that the block
   * scripts and styles for both frontend and backend are
   * enqueued when the editor loads.
   *
   * @link https://wordpress.org/gutenberg/handbook/blocks/writing-your-first-block-type#enqueuing-block-scripts
   * @since 1.16.0
   */
  register_block_type(
    'ireta/card', array(
      'style'           => 'ireta_blocks-cgb-style-css', // Enqueue blocks.style.build.css on both frontend & backend.
      'editor_style'    => 'ireta_blocks-cgb-block-editor-css', // Enqueue blocks.editor.build.css in the editor only.
      'editor_script'   => 'ireta_blocks-cgb-block-js', // Enqueue blocks.build.js in the editor only.
      'render_callback' => 'ireta_blocks_render',
      'attributes'      => array(
        'archiveType'   => array(
          'type'    => 'string',
          'default' => 'posts'
        ),
        'limit'         => array(
          'type'    => 'integer',
          'default' => 12
        ),
        'filter'        => array(
          'type'    => 'boolean',
          'default' => false
        ),
        'selectedPosts' => array(
          'type'    => 'array',
          'default' => array()
        )
      )
    )
  );
}

// Hook: Block assets.
add_action( 'init', 'ireta_blocks_cgb_block_assets' );
``` 

I ended up putting some additional CSS that adds "height" and "width" to the display of the "X". Here it is when not focused in the input:
![image](https://user-images.githubusercontent.com/71997022/118665778-98cb5b80-b7c0-11eb-9c08-6109db96a597.png)

When focused:
![image](https://user-images.githubusercontent.com/71997022/118666073-de882400-b7c0-11eb-9c18-99e117733c71.png)

I think this works quite well actually, which made me think that it was a new feature rather than a mistake.

**Comment by rmorse** [comment]
@dwtompkins - thanks for all the info...  it's still not clear to me what's going wrong.

My assumption is, something in your setup, is not loading required dependencies (js/css) or is loading something that interfers with the styling/behaviours.

As this field is heavily based on the `<FormTokenField />` , I beginning to think that you will see the same issues if you use that?
https://developer.wordpress.org/block-editor/reference-guides/components/form-token-field/

Try copying and pasting [their ](https://developer.wordpress.org/block-editor/reference-guides/components/form-token-field/#usage)demo code, and copying and pasting[ our](https://github.com/rmorse/wp-token-multiselect-control#usage) demo code - and check to see if they have similar issues?

I assume they would, which will give a clue in which direction to continue debugging.

Best

**Comment by rmorse** [comment]
Closing for now as I didn't hear back, and it sounds like an isolated case.
