### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by HardeepAsrani** [rmorse/wp-token-multiselect-control#2]
I really wanted to use this. I came across the same limitations and was going to make my own modifications and then I came across this. Can you publish it to npm so that it's easily usable by everyone?

Good work!

**Comment by rmorse** [comment]
Hey @HardeepAsrani 

Yeah I was thinking of doing this for a little while (but thought this would be replaced by now by native gutenberg components)... 

Looks like that is taking longer than expected, so yeah, I think I will publish :)

I'll report back here when its done, probably over the next week or two.

Thanks

**Comment by matteo-de-carli** [comment]
Are there any news on this?

**Comment by rmorse** [comment]
I didn't get around to doing this - however, I see that the latest version of the Gutenberg plugin changes some styling and breaks this widget (we don't add any styling, just use the classes shipped with Gutenberg).

So when I get around to fixing this I will likely also publish to npm

**Comment by matteo-de-carli** [comment]
Thank you very much!

I also wanted to let you know that for the time being, your Control seems to be working fine for me:
![image](https://user-images.githubusercontent.com/82890427/195565857-a687c976-8ccf-482a-9c94-7e24f0d542b7.png)

**Comment by rmorse** [comment]
Ah ok... I thought with WP core it was fine, but when I updated the Gutenberg feature plugin last week, I noticed something was not right with this control.

I'll need to double check that anyway - thanks for the update

**Comment by rmorse** [comment]
I've started creating a [block editor component library](https://github.com/Code-Amp/block-components) - which is [also published to npm](https://www.npmjs.com/package/@codeamp/block-components), and contains an updated version of this multi-select control.

Resolving this in favor of the new project.
